---
- hosts: webservers
  become: true
  tasks:
  
    - name: Install Docker (if not already installed)
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Pull the PHP project Docker image
      docker_image:
        name: localhost:5000/my-php-app:latest

        tag: latest
        source: pull

    - name: Stop existing PHP container (if any)
      docker_container:
        name: php-app-container
        state: stopped
        force_kill: yes
        remove: yes

    - name: Run the PHP project container
      docker_container:
        name: php-app-container
        image: my-docker-repo/my-php-app:latest
        state: started
        restart_policy: always
        ports:
          - "80:80"  # Map port 80 on the host to port 80 in the container
        volumes:
          - /path/on/host:/path/in/container  # Optional: mount volumes if needed

    - name: Ensure the PHP container is running
      docker_container:
        name: php-app-container
        state: started
        restart_policy: always
